#
# k8s-cms
# Kubernetes Intergration
# Helm Chart
# 

# chart metadata 
apiVersion: v2
appVersion: "1.4.rc1"
type: application
name: k8s-cms
description: Chart to deploy Contest Managment System on Kubernetes.
version: 0.3.0
sources:
- "https://github.com/mrzzy/cms.git"
- "https://github.com/cms-dev/con_test.git"
- "https://github.com/vishnubob/wait-for-it.git"

# chart dependencies
dependencies:
- name: ingress-nginx
  version: 4.4.2
  repository: https://kubernetes.github.io/ingress-nginx
  condition: nginx-ingress.enabled
- name: cert-manager
  version: 1.10.2
  repository: https://charts.jetstack.io
  condition: cert-manager.enabled
- name: kube-prometheus-stack
  version: 43.2.1
  repository: https://prometheus-community.github.io/helm-charts 
  condition: prometheus-operator.enabled
