#
# k8s-cms
# Docker Compose 
# 

version: '3'
services:
  # database
  cms-db:
    build: 
      context: .
      dockerfile: containers/cms-db/Dockerfile
    image: "docker.io/mrzzy/cms-db:latest"
    expose:
    - "5432"
    env_file: 
      - ".env"
      - "config/config.env"
    environment:
      - CMS_DB=0.0.0.0
    volumes:
      - db-data:/var/lib/postgresql/data

  # core cms services
  cms-log:
    build: 
      context: .
      dockerfile: containers/cms-log/Dockerfile
    image: "docker.io/mrzzy/cms-log:latest"
    env_file: 
      - ".env"
      - "config/config.env"
    expose:
      - "29000"
    depends_on:
      - cms-db
  cms-scoring:
    build: 
      context: .
      dockerfile: containers/cms-scoring/Dockerfile
    image: "docker.io/mrzzy/cms-scoring:latest"
    env_file: 
      - ".env"
      - "config/config.env"
    expose:
      - "28500"
    depends_on:
      - cms-db
  cms-resource:
    build: 
      context: .
      dockerfile: containers/cms-resource/Dockerfile
    image: "docker.io/mrzzy/cms-resource:latest"
    env_file: 
      - ".env"
      - "config/config.env"
    expose:
      - "28000"
    depends_on:
      - cms-db
  cms-proxy:
    build: 
      context: .
      dockerfile: containers/cms-proxy/Dockerfile
    image: "docker.io/mrzzy/cms-proxy:latest"
    env_file: 
      - ".env"
      - "config/config.env"
    expose:
      - "28600"
    depends_on:
      - cms-db
      - cms-web-ranking
  cms-printing:
    build: 
      context: .
      dockerfile: containers/cms-printing/Dockerfile
    image: "docker.io/mrzzy/cms-printing:latest"
    env_file: 
      - ".env"
      - "config/config.env"
    expose:
      - "25123"
    depends_on:
      - cms-db
  cms-evaluation:
    build: 
      context: .
      dockerfile: containers/cms-evaluation/Dockerfile
    image: "docker.io/mrzzy/cms-evaluation:latest"
    env_file: 
      - ".env"
      - "config/config.env"
    expose:
      - "25000"
    depends_on:
      - cms-db
  cms-checker:
    build: 
      context: .
      dockerfile: containers/cms-checker/Dockerfile
    image: "docker.io/mrzzy/cms-checker:latest"
    env_file: 
      - ".env"
      - "config/config.env"
    expose:
      - "22000"
    depends_on:
      - cms-db
      - cms-log
      - cms-scoring
      - cms-resource
      - cms-proxy
      - cms-printing
      - cms-evaluation
      - cms-web-admin
      - cms-web-ranking
      - cms-web-contest
      - cms-worker-0
      - cms-worker-1
        
  # web services
  cms-web-ranking:
    build: 
      context: .
      dockerfile: containers/cms-web-ranking/Dockerfile
    image: "docker.io/mrzzy/cms-web-ranking:latest"
    env_file: 
      - ".env"
      - "config/config.env"
    ports:
      - "8890:8890"
    depends_on:
      - cms-db
  cms-web-admin:
    build: 
      context: .
      dockerfile: containers/cms-web-admin/Dockerfile
    image: "docker.io/mrzzy/cms-web-admin:latest"
    ports:
      - "8889:8889"
    expose:
      - "21100"
    env_file: 
      - ".env"
      - "config/config.env"
    depends_on:
      - cms-db
  cms-web-contest:
    build: 
      context: .
      dockerfile: containers/cms-web-contest/Dockerfile
    image: "docker.io/mrzzy/cms-web-contest:latest"
    ports:
      - "8888:8888"
    expose:
      - "21000"
    env_file: 
      - ".env"
      - "config/config.env"
    depends_on:
      - cms-db

  # workers
  cms-worker-0:
    build:
      context: .
      dockerfile: containers/cms-worker/Dockerfile
    image: "docker.io/mrzzy/cms-worker:latest"
    expose:
      - "26000"
    env_file: 
      - ".env"
      - "config/config.env"
    environment:
      - CMS_WORKER_NAME=cms-worker-0
      - CMS_WORKER_0=0.0.0.0
    depends_on:
      - cms-db
    privileged: true

  cms-worker-1:
    build:
      context: .
      dockerfile: containers/cms-worker/Dockerfile
    image: "docker.io/mrzzy/cms-worker:latest"
    expose:
      - "26000"
    env_file: 
      - ".env"
      - "config/config.env"
    environment:
      - CMS_WORKER_NAME=cms-worker-1
      - CMS_WORKER_1=0.0.0.0
    depends_on:
      - cms-db
    privileged: true

  # k8s-cms master
  k8s-cms-master:
    build:
      context: .
      dockerfile: containers/k8s-cms-master/Dockerfile
    image: "docker.io/mrzzy/k8s-cms-master:latest"
    ports:
      - "5000:5000"
    env_file: 
      - ".env"
      - "config/config.env"
    depends_on:
      - cms-db
    
volumes:
  db-data:
